fix en jenkinsfile qa

diff --git a/Jenkinsfile.qa b/Jenkinsfile.qa
--- a/Jenkinsfile.qa
+++ b/Jenkinsfile.qa
@@ -6,88 +6,87 @@ pipeline {
         DOCKER_IMAGE = 'microservicio-qa'
     }
 
-    // Declarar latestCommit en el ámbito global
-    def latestCommit = ''
-
     stages {
         stage('Check if Docker Image Needs to be Built') {
-            steps {
-                script {
-                    // Obtener el hash del último commit
-                    latestCommit = sh(script: 'git rev-parse HEAD', returnStdout: true).trim()
+      steps {
+        script {
+          // Obtener el hash del último commit
+          def latestCommit = sh(script: 'git rev-parse HEAD', returnStdout: true).trim()
 
-                    // Comparar con el hash guardado de la última imagen creada
-                    def previousCommit = sh(script: "docker inspect --format='{{index .Config.Labels \"commit\"}}' ${DOCKER_IMAGE}:latest || echo ''", returnStdout: true).trim()
+          // Comparar con el hash guardado de la última imagen creada
+          def previousCommit = sh(script: "docker inspect --format='{{index .Config.Labels \"commit\"}}' ${DOCKER_IMAGE}:latest || echo ''", returnStdout: true).trim()
 
-                    if (latestCommit == previousCommit) {
-                        echo 'No changes detected since the last Docker image build. Skipping Docker build.'
-                        currentBuild.result = 'SUCCESS'
-                        return // Detener la ejecución del pipeline
+          if (latestCommit == previousCommit) {
+            echo 'No changes detected since the last Docker image build. Skipping Docker build.'
+            currentBuild.result = 'SUCCESS'
+            return // Detener la ejecución del pipeline
                     } else {
-                        echo 'Changes detected. Proceeding to build the Docker image.'
-                    }
-                }
-            }
+            echo 'Changes detected. Proceeding to build the Docker image.'
+          }
+        }
+      }
         }
 
         stage('Stop and Remove Old Container') {
-            steps {
-                script {
-                    try {
-                        // Intentamos detener y eliminar el contenedor antiguo si existe
+      steps {
+        script {
+          try {
+            // Intentamos detener y eliminar el contenedor antiguo si existe
             sh 'docker stop --time=10 ${DOCKER_IMAGE} || true' // || true asegura que no falle si no existe
-                        sh 'docker rm ${DOCKER_IMAGE} || true'   // || true asegura que no falle si no existe
+            sh 'docker rm ${DOCKER_IMAGE} || true'   // || true asegura que no falle si no existe
                     } catch (Exception e) {
-                        echo "No existing container found or other error: ${e}"
-                    }
-                }
-            }
+            echo "No existing container found or other error: ${e}"
+          }
+        }
+      }
         }
 
         stage('Checkout') {
-            steps {
-                git branch: "${BRANCH_NAME}", url: 'https://github.com/ignavela/test-cicd.git'
-            }
+      steps {
+        git branch: "${BRANCH_NAME}", url: 'https://github.com/ignavela/test-cicd.git'
+      }
         }
 
         stage('Build Docker Image') {
-            steps {
-                script {
-                    // Construir la imagen de Docker y etiquetar con el último commit
-                    latestCommit = sh(script: 'git rev-parse HEAD', returnStdout: true).trim()
-                    sh "docker build . -t ${DOCKER_IMAGE}:latest -t ${DOCKER_IMAGE}:${latestCommit}"
-                }
-            }
+      steps {
+        script {
+          // Construir la imagen de Docker y etiquetar con el último commit
+          def latestCommit = sh(script: 'git rev-parse HEAD', returnStdout: true).trim()
+          sh "docker build . -t ${DOCKER_IMAGE}:latest -t ${DOCKER_IMAGE}:${latestCommit}"
+        }
+      }
         }
 
         stage('Deploy to QA') {
-            steps {
-                echo 'Desplegando la imagen en QA...'
-                sh 'docker run -d -p 8082:8081 --name ${DOCKER_IMAGE} ${DOCKER_IMAGE}:latest'
-            }
+      steps {
+        echo 'Desplegando la imagen en QA...'
+        sh 'docker run -d -p 8082:8081 --name ${DOCKER_IMAGE} ${DOCKER_IMAGE}:latest'
+      }
         }
 
         stage('Cleanup Old Docker Images') {
-            steps {
-                script {
-                    // Mantener las últimas 5 imágenes y eliminar las anteriores
-                    def images = sh(
+      steps {
+        script {
+          // Obtener el hash del último commit
+          def latestCommit = sh(script: 'git rev-parse HEAD', returnStdout: true).trim()
+          // Mantener las últimas 5 imágenes y eliminar las anteriores
+          def images = sh(
                         script: "docker images --format '{{.Repository}}:{{.Tag}} {{.CreatedAt}}' | grep '^${DOCKER_IMAGE}' | grep -v '${latestCommit}' | sort -r | tail -n +6",
                         returnStdout: true
                     ).trim()
 
-                    if (images) {
-                        // Convertir la lista de imágenes a una lista de strings y eliminar
-                        def oldImages = images.split('\n')
-                        oldImages.each { image ->
-                            def imageName = image.split(' ')[0]
-                            sh "docker rmi -f ${imageName}"
-                        }
-                    } else {
-                        echo 'No old images to remove.'
-                    }
-                }
+          if (images) {
+            // Convertir la lista de imágenes a una lista de strings y eliminar
+            def oldImages = images.split('\n')
+            oldImages.each { image ->
+              def imageName = image.split(' ')[0]
+              sh "docker rmi -f ${imageName}"
             }
+                    } else {
+            echo 'No old images to remove.'
+          }
+        }
+      }
         }
     }
 }
