fix en jenkinsfile prod

diff --git a/Jenkinsfile.prod b/Jenkinsfile.prod
--- a/Jenkinsfile.prod
+++ b/Jenkinsfile.prod
@@ -38,70 +38,78 @@ pipeline {
         }
 
         stage('Stop and Remove Old Container') {
-      when {
-        expression { shouldProceed }
-      }
-      steps {
-        script {
-          try {
-            // Intentamos detener y eliminar el contenedor antiguo si existe
-            sh 'docker stop --time=10 ${DOCKER_IMAGE} || true' // || true asegura que no falle si no existe
-            sh 'docker rm ${DOCKER_IMAGE} || true'   // || true asegura que no falle si no existe
+          if (shouldProceed) {
+            steps {
+          script {
+            try {
+              // Intentamos detener y eliminar el contenedor antiguo si existe
+              sh 'docker stop --time=10 ${DOCKER_IMAGE} || true' // || true asegura que no falle si no existe
+              sh 'docker rm ${DOCKER_IMAGE} || true'   // || true asegura que no falle si no existe
                     } catch (Exception e) {
-            echo "No existing container found or other error: ${e}"
+              echo "No existing container found or other error: ${e}"
+            }
           }
-        }
-      }
+            }
+          }
+          else {
+            echo 'Skipping stage because Docker image already exists'
+          }
         }
 
         stage('Build Docker Image') {
-      when {
-        expression { shouldProceed }
-      }
-      steps {
-        script {
-          // Construir la imagen de Docker y etiquetar con el último commit
-          def latestCommit = sh(script: 'git rev-parse HEAD', returnStdout: true).trim()
-          sh "docker build . -t ${DOCKER_IMAGE}:latest -t ${DOCKER_IMAGE}:${latestCommit}"
-        }
-      }
+          if (shouldProceed) {
+            steps {
+          script {
+            // Construir la imagen de Docker y etiquetar con el último commit
+            def latestCommit = sh(script: 'git rev-parse HEAD', returnStdout: true).trim()
+            sh "docker build . -t ${DOCKER_IMAGE}:latest -t ${DOCKER_IMAGE}:${latestCommit}"
+          }
+            }
+          }
+          else {
+            echo 'Skipping stage because Docker image already exists'
+          }
         }
 
         stage('Deploy to PROD') {
-      when {
-        expression { shouldProceed }
+      if (shouldProceed) {
+        steps {
+          echo 'Desplegando la imagen en QA...'
+          sh 'docker run -d -p 8082:8081 --name ${DOCKER_IMAGE} ${DOCKER_IMAGE}:latest'
+        }
       }
-      steps {
-        echo 'Desplegando la imagen en QA...'
-        sh 'docker run -d -p 8082:8081 --name ${DOCKER_IMAGE} ${DOCKER_IMAGE}:latest'
+      else {
+        echo 'Skipping stage because Docker image already exists'
       }
         }
 
         stage('Cleanup Old Docker Images') {
-      when {
-        expression { shouldProceed }
-      }
-      steps {
-        script {
-          // Obtener el hash del último commit
-          def latestCommit = sh(script: 'git rev-parse HEAD', returnStdout: true).trim()
-          // Mantener las últimas 5 imágenes y eliminar las anteriores
-          def images = sh(
+      if (shouldProceed) {
+        steps {
+          script {
+            // Obtener el hash del último commit
+            def latestCommit = sh(script: 'git rev-parse HEAD', returnStdout: true).trim()
+            // Mantener las últimas 5 imágenes y eliminar las anteriores
+            def images = sh(
                         script: "docker images --format '{{.Repository}}:{{.Tag}} {{.CreatedAt}}' | grep '^${DOCKER_IMAGE}' | grep -v '${latestCommit}' | sort -r | tail -n +6",
                         returnStdout: true
                     ).trim()
 
-          if (images) {
-            // Convertir la lista de imágenes a una lista de strings y eliminar
-            def oldImages = images.split('\n')
-            oldImages.each { image ->
-              def imageName = image.split(' ')[0]
-              sh "docker rmi -f ${imageName}"
-            }
+            if (images) {
+              // Convertir la lista de imágenes a una lista de strings y eliminar
+              def oldImages = images.split('\n')
+              oldImages.each { image ->
+                def imageName = image.split(' ')[0]
+                sh "docker rmi -f ${imageName}"
+              }
                     } else {
-            echo 'No old images to remove.'
+              echo 'No old images to remove.'
+            }
           }
         }
+      }
+      else {
+        echo 'Skipping stage because Docker image already exists'
       }
         }
     }
